### ISSUE TITLE
Unable to create ECDSA-P521 key

### ISSUE THREAD

**Issue by youk** [unreality/nCryptAgent#11]
Getting the following message when trying to create a ECDSA-P521 key:
```
unable to create persisted key: NCryptCreatePersistedKey
returned NTE_NOT_SUPPORTED: The system cannot find the file specified.
```
The log file has no related info.

Windows 10 Pro 22H2

**Comment by unreality** [comment]
nCryptAgent always attempts to use the TPM, and most TPM chips (or fTPM) only support ECDSA-256.

Things like yubikeys may support different algorithms which is why the options exist.

I'll merge this into another issue for generating a better error, or interrogating the TPM to find out what algorithms/lengths are available.
